name: waves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - owslib
  - pandas
  - iris
  - ioos_tools
  - pyoos
  - retrying
  - geolinks
  - netcdf4
  - matplotlib
  - folium
  - bokeh
  - nb_conda_kernels