channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - owslib
  - lxml
  - pandas
  - iris
  - ioos_tools
  - netcdf4
  - matplotlib
  - folium
  - bokeh
  - np_conda_kernels